### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by VVh5912** [pschaldenbrand/AniPainter#1]
Hi,
First at all, this is absolutely a piece of great work! I love the results of the AniPainter and I was trying to implement the paint.py file in Colab.
This is the issue I got when implementing it. I am new in python, can you please help me on this?

Traceback (most recent call last):
  File "paint.py", line 655, in <module>
    output_dir=args.output_dir, w=args.w, h=args.h)
  File "paint.py", line 594, in paint_fn
    save_strokes_for_robot(s, img, painting.cpu().numpy(), allowed_colors, ignore_whites=ignore_whites, output_dir=output_dir)
  File "paint.py", line 182, in save_strokes_for_robot
    S_whites = np.array(copy.deepcopy(S))
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 732, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by pschaldenbrand** [comment]
Hi @VVh5912 ! I'm glad you enjoy the work :)

I suspect that Colab uses a different version of pytorch or python than I am using in my local environment because I do not get this error when I run paint.py on my local machine.  Would you be able to share the colab notebook with me so I can try some steps to debug this?

I think a quick/dirty fix is to disable GPU usage.  In Colab you can change the runtime type to not have a GPU.  Alternatively, in line 23 of paint.py, you can change it to just use CPU: `device = torch.device('cpu')` 

As for what I think would fix this error: I think the elements of S need to be out of the gpu when copying them on the error line.  I think this can be fixed by adding the following line right before line 180 of paint.py:

```
# Remove white strokes if specified
S = [list(s[:10]) + [s[10].cpu(),s[11].cpu(),s[12].cpu()]  for s in S] # To CPU
if ignore_whites:
```
If I can gain access to your Colab notebook, I can test this out.

**Comment by VVh5912** [comment]
Hi!
Thank you for you reply. Can I know what version of pytorch you are using in your environment?
Here is my Colab notebook:

[https://colab.research.google.com/drive/1YzEmXIsv3nYMyS0BESOHlDu2Df4PJrtA?usp=sharing](url)

**Comment by pschaldenbrand** [comment]
It looks like AniPainter isn't compatible with some newer versions of torch.  I added the following line to your notebook and it worked for me. Please let me know if this fixes the issue.  

```
!pip install torch==1.4.0 numpy==1.16.2 torchvision==0.5.0 pandas==1.0.5
```

Also, I would love to share a link to the colab notebook when you're ready if you'd be willing to share! I think it would be very helpful for other people to see it.  Please let me know if you'd be willing and I can link it in the ReadMe :)

**Comment by VVh5912** [comment]
Thank you, it works! Yes, please feel free to share it.
Also, I would like to know what parameters should I choose for to achieve something like "atta_no_style_painted.gif" in your directory. The strokes are very different from "atta_no_style_sbr.gif".

**Comment by pschaldenbrand** [comment]
"atta_no_style_painted.gif" was physically painted by a robot. The robot painted based off the simulated environment that produced "atta_no_style_sbr.gif".  There is info in the readme about the robot system.

**Comment by VVh5912** [comment]
Ok sure! Thank you again, this helps me a lot.

**Comment by onyedikilo** [comment]
I got the same error, solved it by modifying the copy.deepcopy commands like :

`S_whites = np.array(copy.deepcopy(torch.tensor(S).detach().cpu().numpy()))`

`S = np.array(copy.deepcopy(torch.tensor(S).detach().cpu().numpy()))`
